elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000

    kinematic_controller:
      type: arm_controllers/Kinematic_Controller
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      gains:
        elfin_joint1:
          pid: {p: 80.0, i: 0, d: 5.0}
          p_gain: {p: 15.0}
        elfin_joint2:
          pid: {p: 80.0, i: 0, d: 5.0}
          p_gain: {p: 15.0}
        elfin_joint3:
          pid: {p: 80.0, i: 0, d: 5.0}
          p_gain: {p: 15.0}
        elfin_joint4:
          pid: {p: 80.0, i: 0, d: 5.0}
          p_gain: {p: 0.0}
        elfin_joint5:
          pid: {p: 80.0, i: 0, d: 5.0}
          p_gain: {p: 0.0}
        elfin_joint6:
          pid: {p: 80.0, i: 0, d: 5.0}
          p_gain: {p: 0.0}
      root_link: world
      tip_link: elfin_link6
