elfin:
    obsavoid_controller:
      joint_limits:
        elfin_joint1:
          has_position_limits: true
          min_position: 0.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 1.57
          has_acceleration_limits: false
          max_acceleration: 5.0
          has_jerk_limits: false
          max_jerk: 100.0
          has_effort_limits: false
          max_effort: 20.0
        elfin_joint2:
          has_position_limits: true
          min_position: 0.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 1.57
          has_acceleration_limits: false
          max_acceleration: 5.0
          has_jerk_limits: false
          max_jerk: 100.0
          has_effort_limits: false
          max_effort: 20.0
        elfin_joint3:
          has_position_limits: true
          min_position: 0.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 1.57
          has_acceleration_limits: false
          max_acceleration: 5.0
          has_jerk_limits: false
          max_jerk: 100.0
          has_effort_limits: false
          max_effort: 20.0
        elfin_joint4:
          has_position_limits: true
          min_position: 0.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 1.57
          has_acceleration_limits: false
          max_acceleration: 5.0
          has_jerk_limits: false
          max_jerk: 100.0
          has_effort_limits: false
          max_effort: 20.0
        elfin_joint5:
          has_position_limits: true
          min_position: 0.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 1.57
          has_acceleration_limits: false
          max_acceleration: 5.0
          has_jerk_limits: false
          max_jerk: 100.0
          has_effort_limits: false
          max_effort: 20.0
        elfin_joint6:
          has_position_limits: true
          min_position: 0.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 1.57
          has_acceleration_limits: false
          max_acceleration: 5.0
          has_jerk_limits: false
          max_jerk: 100.0
          has_effort_limits: false
          max_effort: 20.0
    

