elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000

    table_avoid_whole_controller:
      type: arm_controllers/TableAvoidWhole_Controller
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      links:
        - elfin_link1
        - elfin_link2
        - elfin_link3
        - elfin_link4
        - elfin_link5
        - elfin_link6
        - elfin_end_link
      gains:
        x:
          pid: {p: 200.0, i: 0, d: 20.0}
        y:
          pid: {p: 200.0, i: 0, d: 20.0}
        z:
          pid: {p: 200.0, i: 0, d: 20.0}
        roll:
          pid: {p: 200.0, i: 0, d: 20.0}
        pitch:
          pid: {p: 200.0, i: 0, d: 20.0}
        yaw:
          pid: {p: 200.0, i: 0, d: 20.0}

      root_link: world
      tip_link: elfin_end_link
