elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000

    table_avoid_controller:
      type: arm_controllers/TableAvoid_Controller
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      gains:
        x:
          pid: {p: 100.0, i: 0, d: 20.0}
        y:
          pid: {p: 100.0, i: 0, d: 20.0}
        z:
          pid: {p: 100.0, i: 0, d: 20.0}
        roll:
          pid: {p: 100.0, i: 0, d: 20.0}
        pitch:
          pid: {p: 100.0, i: 0, d: 20.0}
        yaw:
          pid: {p: 100.0, i: 0, d: 20.0}
      root_link: world
      tip_link: elfin_link6
